spring.application.name=K23CNT1-Mba-Day07
spring.datasource.url=jdbc:mysql://localhost:3306/lesson07db
spring.datasource.username=root
spring.datasource.password=Anmysql10101@@@
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
